### ISSUE TITLE
pcname = os.getenv('username')

### ISSUE THREAD

**Issue by AffeMitWaff** [extremedevalt/KeyLogger-TokenGrabber-IpGrabber#5]
[1/1] Webhook status code 400: {"username": ["Must be between 1 and 80 in length."]}
what do i have to write there
pasting the username isnt helping

**Comment by ExtremeDude-tech** [comment]
Here you have to put an username, that should be the error, so for example your Webhook name is Test, put Test there!

**Comment by AffeMitWaff** [comment]
k thank u

**Comment by AstroOrbis** [comment]
@extremedevalt Close #5
